export const awsServices = [
  {
    id: "billing",
    name: "Billing",
    description: "Cost Management and Budgeting",
    icon: "💰",
    color: "from-orange-500 to-red-500",
    hoverColor: "from-orange-600 to-red-600",
    topics: [
      "Cost Explorer",
      "Budget Management",
      "Billing Alerts",
    ],
  },
  {
    id: "s3",
    name: "Manage Alarms",
    description: "Alarm Management and Monitoring",
    icon: "🔔",
    color: "from-green-500 to-teal-500",
    hoverColor: "from-green-600 to-teal-600",
    topics: [
      "Alarm Configuration",
      "Notification Setup",
      "Threshold Management",
    ],
  },
  {
    id: "reports",
    name: "Reports",
    description: "Service Performance Analytics",
    icon: "📊",
    color: "from-blue-500 to-indigo-500",
    hoverColor: "from-blue-600 to-indigo-600",
    topics: [
      "Performance Metrics",
      "Resource Utilization",
      "Cost Analysis",
    ],
  },
  {
    id: "services",
    name: "Services Running",
    description: "Active Service Management",
    icon: "⚡",
    color: "from-yellow-500 to-orange-500",
    hoverColor: "from-yellow-600 to-orange-600",
    topics: [
      "Service Status",
      "Resource Health",
      "Performance Monitoring",
    ],
  },
  {
    id: "monitor-logs",
    name: "Monitor Server Logs",
    description: "Server Log Analysis & Tracking",
    icon: "📋",
    color: "from-purple-500 to-pink-500",
    hoverColor: "from-purple-600 to-pink-600",
    topics: [
      "Real-time Log Monitoring",
      "Error Tracking",
      "Performance Logs",
    ],
  },
  {
    id: "cloudtrail",
    name: "CloudTrail",
    description: "Activity & Audit Logging",
    icon: "🔍",
    color: "from-red-500 to-pink-500",
    hoverColor: "from-red-600 to-pink-600",
    topics: [
      "Activity Monitoring",
      "Audit Logs",
      "Security Analysis",
    ],
  },
];
