export const awsServices = [
  {
    id: "ec2",
    name: "Amazon EC2",
    description: "Virtual Servers in the Cloud",
    icon: "🖥️",
    color: "from-orange-500 to-red-500",
    hoverColor: "from-orange-600 to-red-600",
    topics: [
      "Instance Types & Families",
      "Auto Scaling Groups",
      "Load Balancing",
      "Security Groups & Network ACLs",
      "Storage Options (EBS)",
      "Instance Lifecycle",
    ],
  },
  {
    id: "s3",
    name: "Amazon S3",
    description: "Scalable Storage in the Cloud",
    icon: "📦",
    color: "from-green-500 to-teal-500",
    hoverColor: "from-green-600 to-teal-600",
    topics: [
      "Bucket Management",
      "Object Lifecycle",
      "Storage Classes",
      "Access Control & Policies",
      "Versioning",
      "Data Encryption",
    ],
  },
  {
    id: "rds",
    name: "Amazon RDS",
    description: "Managed Relational Database Service",
    icon: "🗄️",
    color: "from-blue-500 to-indigo-500",
    hoverColor: "from-blue-600 to-indigo-600",
    topics: [
      "Database Engines",
      "Instance Management",
      "Backup & Recovery",
      "Multi-AZ Deployment",
      "Read Replicas",
      "Performance Insights",
    ],
  },
  {
    id: "lambda",
    name: "AWS Lambda",
    description: "Serverless Computing",
    icon: "λ",
    color: "from-yellow-500 to-orange-500",
    hoverColor: "from-yellow-600 to-orange-600",
    topics: [
      "Function Development",
      "Event Sources",
      "Execution Environment",
      "Monitoring & Logging",
      "Security & Permissions",
      "Best Practices",
    ],
  },
  {
    id: "cloudwatch",
    name: "Amazon CloudWatch",
    description: "Monitoring & Observability",
    icon: "📊",
    color: "from-purple-500 to-pink-500",
    hoverColor: "from-purple-600 to-pink-600",
    topics: [
      "Metrics & Dimensions",
      "Alarms Configuration",
      "Logs Insights",
      "Dashboards",
      "Events & EventBridge",
      "Container Insights",
    ],
  },
  {
    id: "iam",
    name: "AWS IAM",
    description: "Identity & Access Management",
    icon: "🔐",
    color: "from-red-500 to-pink-500",
    hoverColor: "from-red-600 to-pink-600",
    topics: [
      "Users & Groups",
      "Roles & Policies",
      "Permission Management",
      "Security Best Practices",
      "Access Keys",
      "Identity Federation",
    ],
  },
];
